server:
  name: "zabbix-api"
  mode: "debug"
  port: 8888

log:
  level: "debug"
  filename: "log/jarvis.log"
  max_siz: 1
  max_age: 30
  max_backups: 7

redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""



